CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260605125740_CreateWeatherForecastTable') THEN
    CREATE TABLE "WeatherForecasts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Date" date NOT NULL,
        "TemperatureC" integer NOT NULL,
        "Summary" text,
        CONSTRAINT "PK_WeatherForecasts" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260605125740_CreateWeatherForecastTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260605125740_CreateWeatherForecastTable', '10.0.3');
    END IF;
END $EF$;
COMMIT;

