START TRANSACTION;

CREATE TABLE public.ea_followup_cycles (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "FollowupId" bigint NOT NULL,
    "SequenceNumber" integer NOT NULL,
    "FollowedUpAt" timestamp with time zone NOT NULL,
    "Note" character varying(2000),
    "NextFollowupAt" timestamp with time zone,
    "ExpectedResponseAt" timestamp with time zone,
    "OutcomeCode" character varying(100),
    "CreatedBy" character varying(100) NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ea_followup_cycles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ea_followup_cycles_ea_followups_FollowupId" FOREIGN KEY ("FollowupId") REFERENCES public.ea_followups ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_ea_followup_cycles_FollowupId_SequenceNumber" ON public.ea_followup_cycles ("FollowupId", "SequenceNumber");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260909053125_AddEaFmsFollowupCycles', '8.0.30');

COMMIT;

