<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<IsPackable>false</IsPackable>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.30" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.30" />
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
	<PackageReference Include="xunit" Version="2.4.1" />
	<PackageReference Include="xunit.runner.visualstudio" Version="2.4.3" />
	  <PackageReference Include="Moq" Version="4.18.4" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Studio5JarvisMasterApi.csproj" />
  </ItemGroup>
</Project>
