// <auto-generated />
using System;
using Jarvis5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jarvis5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803102400_AddOverallDatesToScihRequest")]
    partial class AddOverallDatesToScihRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("scih_request_no_seq");

            modelBuilder.Entity("Jarvis5.Entities.SCIHAnalysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AnalysisJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<string>("ComparisonJson")
                        .HasColumnType("jsonb");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("GeneratedByModel")
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp");

                    b.Property<long?>("PreviousAnalysisId")
                        .HasColumnType("bigint");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReworkCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("DRAFT");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("PreviousAnalysisId");

                    b.HasIndex("RequestId");

                    b.HasIndex("RequestId", "Version")
                        .IsUnique();

                    b.ToTable("SCIH_Analysis", (string)null);
                });

            modelBuilder.Entity("Jarvis5.Entities.SCIHApproval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ApprovalRound")
                        .HasColumnType("integer");

                    b.Property<long?>("ApprovedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ImprovementAreasJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("ImprovementAreasJson");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReworkCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("RequestId", "ApprovalRound")
                        .IsUnique();

                    b.ToTable("SCIH_Approval", (string)null);
                });

            modelBuilder.Entity("Jarvis5.Entities.SCIHRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AttachmentsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("AttachmentsJson");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("ExpectedBenefit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MetaJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("MetaJson");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("OverallEndDate")
                        .HasColumnType("timestamp");

                    b.Property<decimal>("OverallProgress")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("OverallStartDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("PainPointsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("PainPointsJson");

                    b.Property<long?>("ParentRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("RaisedBy")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("RequestNo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ParentRequestId");

                    b.HasIndex("Priority");

                    b.HasIndex("RaisedAt");

                    b.HasIndex("RaisedBy");

                    b.HasIndex("RequestNo")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("SCIH_Request", (string)null);
                });

            modelBuilder.Entity("Jarvis5.Entities.SCIHRequestHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<long>("ActionBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("jsonb");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActionDate");

                    b.HasIndex("RequestId");

                    b.ToTable("SCIH_RequestHistory", (string)null);
                });

            modelBuilder.Entity("Jarvis5.Entities.SCIHSolutionDesign", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AIModel")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AttachmentsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("AttachmentsJson");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp");

                    b.Property<long>("GeneratedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("PromptVersion")
                        .HasColumnType("varchar(20)");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("SolutionJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("SCIH_SolutionDesign", (string)null);
                });

            modelBuilder.Entity("Jarvis5.Entities.SCIHStageMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChecklistJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("ChecklistJson");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamptz");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StageName")
                        .IsUnique();

                    b.ToTable("SCIH_StageMaster", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ChecklistJson = "[\"Requirement Reviewed\",\"Flow Prepared\",\"Approved by Lead\"]",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            StageName = "Mind Mapping"
                        },
                        new
                        {
                            Id = 2L,
                            ChecklistJson = "[\"API Created\",\"Validation Completed\",\"Repository Added\",\"Service Added\",\"Unit Testing Completed\"]",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            StageName = "Backend"
                        },
                        new
                        {
                            Id = 3L,
                            ChecklistJson = "[\"Screen Completed\",\"Responsive Completed\",\"API Integrated\",\"Validation Added\"]",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            IsDeleted = false,
                            StageName = "Frontend"
                        },
                        new
                        {
                            Id = 4L,
                            ChecklistJson = "[\"Model Selected\",\"Prompt Designed\",\"Model Integrated\",\"Output Validated\"]",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            IsDeleted = false,
                            StageName = "AI"
                        },
                        new
                        {
                            Id = 5L,
                            ChecklistJson = "[\"Schema Designed\",\"Tables Created\",\"Indexes Added\",\"Migration Verified\"]",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsActive = true,
                            IsDeleted = false,
                            StageName = "Database"
                        },
                        new
                        {
                            Id = 6L,
                            ChecklistJson = "[\"Endpoints Mapped\",\"Integration Completed\",\"Error Handling Verified\",\"Response Validated\"]",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsActive = true,
                            IsDeleted = false,
                            StageName = "API Integration"
                        },
                        new
                        {
                            Id = 7L,
                            ChecklistJson = "[\"Test Cases Prepared\",\"Unit Tests Passed\",\"Bug Fixes Verified\"]",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsActive = true,
                            IsDeleted = false,
                            StageName = "Backend Testing"
                        },
                        new
                        {
                            Id = 8L,
                            ChecklistJson = "[\"Test Cases Prepared\",\"UI Tests Passed\",\"Cross Browser Verified\"]",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 8,
                            IsActive = true,
                            IsDeleted = false,
                            StageName = "Frontend Testing"
                        },
                        new
                        {
                            Id = 9L,
                            ChecklistJson = "[\"Test Dataset Prepared\",\"Accuracy Verified\",\"Edge Cases Tested\"]",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 9,
                            IsActive = true,
                            IsDeleted = false,
                            StageName = "AI Testing"
                        },
                        new
                        {
                            Id = 10L,
                            ChecklistJson = "[\"Build Verified\",\"Deployment Script Ready\",\"Deployed to Server\",\"Smoke Test Passed\"]",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 10,
                            IsActive = true,
                            IsDeleted = false,
                            StageName = "Deployment"
                        },
                        new
                        {
                            Id = 11L,
                            ChecklistJson = "[\"User Guide Prepared\",\"Technical Doc Updated\",\"Reviewed by Lead\"]",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 11,
                            IsActive = true,
                            IsDeleted = false,
                            StageName = "Documentation"
                        },
                        new
                        {
                            Id = 12L,
                            ChecklistJson = "[\"Script Prepared\",\"Recording Completed\",\"Editing Completed\"]",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 12,
                            IsActive = true,
                            IsDeleted = false,
                            StageName = "Video"
                        },
                        new
                        {
                            Id = 13L,
                            ChecklistJson = "[\"Video Reviewed\",\"Audio Verified\",\"Approved by Lead\"]",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 13,
                            IsActive = true,
                            IsDeleted = false,
                            StageName = "Video Testing"
                        },
                        new
                        {
                            Id = 14L,
                            ChecklistJson = "[\"Training Material Prepared\",\"Session Conducted\",\"Feedback Collected\"]",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 14,
                            IsActive = true,
                            IsDeleted = false,
                            StageName = "Training"
                        },
                        new
                        {
                            Id = 15L,
                            ChecklistJson = "[\"Documents Handed Over\",\"Access Provided\",\"Client Sign-off Received\"]",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 15,
                            IsActive = true,
                            IsDeleted = false,
                            StageName = "Handover"
                        });
                });

            modelBuilder.Entity("Jarvis5.Entities.SCIHTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovedId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreationDate")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("DoerLead")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IsDelete")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("false");

                    b.Property<string>("IsDeletedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("OverallEndDate")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OverallStartDate")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SolutionId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StageDetails")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UpdationDate")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStatus");

                    b.HasIndex("RequestId");

                    b.ToTable("SCIH_Task", (string)null);
                });

            modelBuilder.Entity("Jarvis5.Entities.SCIHTaskHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<long>("ActionBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("jsonb");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StageId")
                        .HasColumnType("bigint");

                    b.Property<string>("StageName")
                        .HasColumnType("varchar(100)");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActionDate");

                    b.HasIndex("RequestId");

                    b.HasIndex("TaskId");

                    b.ToTable("SCIH_TaskHistory", (string)null);
                });

            modelBuilder.Entity("Jarvis5.Entities.SCIHAnalysis", b =>
                {
                    b.HasOne("Jarvis5.Entities.SCIHAnalysis", null)
                        .WithMany()
                        .HasForeignKey("PreviousAnalysisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Jarvis5.Entities.SCIHRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Jarvis5.Entities.SCIHApproval", b =>
                {
                    b.HasOne("Jarvis5.Entities.SCIHRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Jarvis5.Entities.SCIHRequestHistory", b =>
                {
                    b.HasOne("Jarvis5.Entities.SCIHRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Jarvis5.Entities.SCIHSolutionDesign", b =>
                {
                    b.HasOne("Jarvis5.Entities.SCIHRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
