// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hrms_api.Data;

#nullable disable

namespace hrms_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623050515_CreateAssessmentEvaluationsTable")]
    partial class CreateAssessmentEvaluationsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hrms_api.Models.AssessmentEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiSummary")
                        .HasColumnType("text");

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("EvaluationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("InterviewId")
                        .HasColumnType("integer");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ManualReviewRequired")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ObtainedMarks")
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Recommendation")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RoundId")
                        .HasColumnType("integer");

                    b.Property<string>("RoundName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strengths")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalMarks")
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Weaknesses")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CandidateId", "InterviewId", "RoundId", "CreatedAt");

                    b.ToTable("AssessmentEvaluations");
                });

            modelBuilder.Entity("hrms_api.Models.AssessmentQuestionBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpectedAnswer")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionNo")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoundName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkillArea")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Weightage")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Department", "Designation", "Level", "RoundName", "IsActive");

                    b.HasIndex("Department", "Designation", "Level", "RoundName", "QuestionNo")
                        .IsUnique()
                        .HasDatabaseName("IX_AssessmentQuestionBanks_Department_Designation_Level_Round~1");

                    b.ToTable("AssessmentQuestionBanks");
                });

            modelBuilder.Entity("hrms_api.Models.CallRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecordingId"));

                    b.Property<string>("CallerName")
                        .HasColumnType("text");

                    b.Property<int?>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecordingContentType")
                        .HasColumnType("text");

                    b.Property<string>("RecordingFileName")
                        .HasColumnType("text");

                    b.Property<string>("RecordingPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RecordingId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("RecordedAt");

                    b.ToTable("CallRecordings");
                });

            modelBuilder.Entity("hrms_api.Models.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CandidateId"));

                    b.Property<int?>("AssignedHRId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentCtcLpa")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("applied");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<decimal?>("ExpectedCtcLpa")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KeySkills")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextFollowUpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoticePeriod")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("RequisitionId")
                        .HasColumnType("integer");

                    b.Property<string>("ResumeContentType")
                        .HasColumnType("text");

                    b.Property<string>("ResumeFileName")
                        .HasColumnType("text");

                    b.Property<string>("ResumePath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ShortlistingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("CandidateId");

                    b.HasIndex("Email");

                    b.HasIndex("RequisitionId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("hrms_api.Models.CandidateAIScreening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AchievementImpactScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CareerStabilityScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("ConcernsJson")
                        .HasColumnType("text");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Decision")
                        .HasColumnType("text");

                    b.Property<decimal?>("EducationCertificationScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<decimal?>("ExperienceRelevanceScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("GrowthPotentialScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("IndustryAlignmentScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("InterviewFocusAreasJson")
                        .HasColumnType("text");

                    b.Property<string>("JDExtractedText")
                        .HasColumnType("text");

                    b.Property<string>("JDPath")
                        .HasColumnType("text");

                    b.Property<string>("MatchedSkillsJson")
                        .HasColumnType("text");

                    b.Property<string>("MissingSkillsJson")
                        .HasColumnType("text");

                    b.Property<decimal?>("OverallScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("RawOllamaResponse")
                        .HasColumnType("text");

                    b.Property<string>("Recommendation")
                        .HasColumnType("text");

                    b.Property<decimal?>("RedFlagDeduction")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("RedFlagsJson")
                        .HasColumnType("text");

                    b.Property<int?>("RequisitionId")
                        .HasColumnType("integer");

                    b.Property<string>("ResumeExtractedText")
                        .HasColumnType("text");

                    b.Property<string>("ResumePath")
                        .HasColumnType("text");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("text");

                    b.Property<decimal?>("RoleFitScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("ShortSummary")
                        .HasColumnType("text");

                    b.Property<decimal?>("SkillFitScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrengthsJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("CandidateId", "Status");

                    b.ToTable("CandidateAIScreenings");
                });

            modelBuilder.Entity("hrms_api.Models.CandidateActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("EvaluationJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("CandidateActivities");
                });

            modelBuilder.Entity("hrms_api.Models.DirectorAiInterviewQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("DiscProfile")
                        .HasColumnType("text");

                    b.Property<string>("GapOrRiskArea")
                        .HasColumnType("text");

                    b.Property<decimal?>("HrRoundScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("IScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("InterviewRoundId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("OverallGapSummary")
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionNo")
                        .HasColumnType("integer");

                    b.Property<string>("RedFlagSignals")
                        .HasColumnType("text");

                    b.Property<decimal?>("SScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("ScreeningScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("StrongAnswerSignals")
                        .HasColumnType("text");

                    b.Property<decimal?>("TechnicalAssessmentScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhyDirectorShouldAskThis")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("InterviewRoundId");

                    b.HasIndex("CandidateId", "InterviewRoundId", "QuestionNo")
                        .IsUnique();

                    b.ToTable("DirectorAiInterviewQuestions");
                });

            modelBuilder.Entity("hrms_api.Models.HiringRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("AcceptableNoticePeriods")
                        .HasColumnType("text");

                    b.Property<decimal?>("BudgetMaxLpa")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("BudgetMinLpa")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("DirectorName")
                        .HasColumnType("text");

                    b.Property<int?>("ExperienceMaxYears")
                        .HasColumnType("integer");

                    b.Property<int?>("ExperienceMinYears")
                        .HasColumnType("integer");

                    b.Property<string>("ExperienceRequired")
                        .HasColumnType("text");

                    b.Property<DateTime?>("HrAcceptDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HrStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsApprovedByDirector")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("JDID")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfPosition")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.Property<string>("ReasonForHiring")
                        .HasColumnType("text");

                    b.Property<string>("RequestById")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RequiredByDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId");

                    b.ToTable("HiringRequests");
                });

            modelBuilder.Entity("hrms_api.Models.HrAiInterviewQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("DiscProfile")
                        .HasColumnType("text");

                    b.Property<decimal?>("IScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("InterviewRoundId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionNo")
                        .HasColumnType("integer");

                    b.Property<string>("RedFlagSignals")
                        .HasColumnType("text");

                    b.Property<decimal?>("SScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("ScoringGuideline")
                        .HasColumnType("text");

                    b.Property<string>("StrongAnswerSignals")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhyAskThis")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("InterviewRoundId");

                    b.HasIndex("CandidateId", "InterviewRoundId", "QuestionNo")
                        .IsUnique();

                    b.ToTable("HrAiInterviewQuestions");
                });

            modelBuilder.Entity("hrms_api.Models.JDMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("DocumentPdfContentType")
                        .HasColumnType("text");

                    b.Property<string>("DocumentPdfFileName")
                        .HasColumnType("text");

                    b.Property<string>("DocumentPdfPath")
                        .HasColumnType("text");

                    b.Property<string>("Experience")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JobDescription")
                        .HasColumnType("text");

                    b.Property<string>("Qualification")
                        .HasColumnType("text");

                    b.Property<string>("SkillsRequired")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Department", "Designation");

                    b.ToTable("JDMasters");
                });

            modelBuilder.Entity("hrms_api.Models.OnboardingTestAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignmentId"));

                    b.Property<string>("AssignedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("integer");

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ObtainedMarks")
                        .HasColumnType("numeric(8,2)");

                    b.Property<int?>("OnboardingId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewRemarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalMarks")
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AssignmentId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("CandidateId", "TemplateId", "AttemptNo");

                    b.ToTable("OnboardingTestAssignments");
                });

            modelBuilder.Entity("hrms_api.Models.OnboardingTestBank", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("DesignationId")
                        .HasColumnType("integer");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Marks")
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Options")
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("QuestionId");

                    b.HasIndex("Category", "DepartmentId", "DesignationId", "IsActive");

                    b.ToTable("OnboardingTestBanks");
                });

            modelBuilder.Entity("hrms_api.Models.OnboardingTestResponse", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ResponseId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer");

                    b.Property<string>("CandidateAnswer")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvaluatedBy")
                        .HasColumnType("text");

                    b.Property<string>("EvaluatorRemarks")
                        .HasColumnType("text");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("ResponseId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("AssignmentId", "QuestionId")
                        .IsUnique();

                    b.ToTable("OnboardingTestResponses");
                });

            modelBuilder.Entity("hrms_api.Models.OnboardingTestTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TemplateId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("DesignationId")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("PassingPercentage")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TemplateId");

                    b.HasIndex("DepartmentId", "DesignationId", "IsActive");

                    b.ToTable("OnboardingTestTemplates");
                });

            modelBuilder.Entity("hrms_api.Models.OnboardingTestTemplateQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Marks")
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TemplateId", "QuestionId")
                        .IsUnique();

                    b.ToTable("OnboardingTestTemplateQuestions");
                });

            modelBuilder.Entity("hrms_api.Models.ScreeningBatch", b =>
                {
                    b.Property<string>("BatchId")
                        .HasColumnType("text");

                    b.Property<string>("CandidateIdsJson")
                        .HasColumnType("text");

                    b.Property<int>("Completed")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Failed")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<bool>("ForceRescreen")
                        .HasColumnType("boolean");

                    b.Property<int>("PendingReview")
                        .HasColumnType("integer");

                    b.Property<int>("Rejected")
                        .HasColumnType("integer");

                    b.Property<int>("Shortlisted")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCandidates")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BatchId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("ScreeningBatches");
                });

            modelBuilder.Entity("hrms_api.Models.Sourcing", b =>
                {
                    b.Property<int>("SourcingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SourcingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HiringRequestId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubSource")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("TaskDetails")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SourcingId");

                    b.HasIndex("HiringRequestId");

                    b.ToTable("Sourcings");
                });

            modelBuilder.Entity("hrms_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("hrms_api.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");
                });

            modelBuilder.Entity("hrms_api.Models.AssessmentEvaluation", b =>
                {
                    b.HasOne("hrms_api.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("hrms_api.Models.CandidateActivity", b =>
                {
                    b.HasOne("hrms_api.Models.Candidate", "Candidate")
                        .WithMany("CandidateActivities")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("hrms_api.Models.OnboardingTestAssignment", b =>
                {
                    b.HasOne("hrms_api.Models.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hrms_api.Models.OnboardingTestTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("hrms_api.Models.OnboardingTestResponse", b =>
                {
                    b.HasOne("hrms_api.Models.OnboardingTestAssignment", "Assignment")
                        .WithMany("Responses")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hrms_api.Models.OnboardingTestBank", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("hrms_api.Models.OnboardingTestTemplateQuestion", b =>
                {
                    b.HasOne("hrms_api.Models.OnboardingTestBank", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("hrms_api.Models.OnboardingTestTemplate", "Template")
                        .WithMany("Questions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("hrms_api.Models.Candidate", b =>
                {
                    b.Navigation("CandidateActivities");
                });

            modelBuilder.Entity("hrms_api.Models.OnboardingTestAssignment", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("hrms_api.Models.OnboardingTestTemplate", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
