using Jarvis5.Data.EaFms;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Studio5JarvisMasterApi.Migrations;

[DbContext(typeof(EaFmsDbContext))]
[Migration("20260915000000_EnsureEaApprovalNumberSequence")]
public partial class EnsureEaApprovalNumberSequence : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS public.ea_approval_requests (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "EaTaskId" bigint NOT NULL UNIQUE REFERENCES public.ea_tasks("Id") ON DELETE RESTRICT,
                "ReferenceNo" varchar(40) NOT NULL UNIQUE,
                "RequestTitle" varchar(500), "RequestType" varchar(200), "RequestedBy" varchar(100),
                "Department" varchar(200), "Priority" varchar(100), "Description" varchar(4000),
                "Justification" varchar(4000), "Amount" numeric(18,2), "Currency" varchar(10),
                "RequiredApprovalDate" timestamp with time zone, "ApproverId" varchar(100),
                "ApproverName" varchar(200), "WorkflowStatus" varchar(100), "CurrentCycleNo" integer NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL, "CreatedBy" varchar(100) NOT NULL,
                "UpdatedAt" timestamp with time zone, "UpdatedBy" varchar(100), "SubmittedAt" timestamp with time zone,
                "ApprovedAt" timestamp with time zone, "RejectedAt" timestamp with time zone,
                "ClosedAt" timestamp with time zone, "IsDeleted" boolean NOT NULL
            );
            CREATE INDEX IF NOT EXISTS "IX_ea_approval_requests_WorkflowStatus" ON public.ea_approval_requests ("WorkflowStatus");
            CREATE INDEX IF NOT EXISTS "IX_ea_approval_requests_ApproverId" ON public.ea_approval_requests ("ApproverId");
            CREATE INDEX IF NOT EXISTS "IX_ea_approval_requests_RequestedBy" ON public.ea_approval_requests ("RequestedBy");
            CREATE INDEX IF NOT EXISTS "IX_ea_approval_requests_RequiredApprovalDate" ON public.ea_approval_requests ("RequiredApprovalDate");
            CREATE INDEX IF NOT EXISTS "IX_ea_approval_requests_CreatedAt" ON public.ea_approval_requests ("CreatedAt");

            CREATE TABLE IF NOT EXISTS public.ea_approval_cycles (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ApprovalRequestId" bigint NOT NULL REFERENCES public.ea_approval_requests("Id") ON DELETE RESTRICT,
                "CycleNo" integer NOT NULL, "SubmittedAt" timestamp with time zone, "SubmittedBy" varchar(100),
                "RequiredApprovalDate" timestamp with time zone, "ApproverId" varchar(100), "Status" varchar(100),
                "ChangeReason" varchar(2000), "DecisionComment" varchar(2000),
                "CreatedAt" timestamp with time zone NOT NULL, "UpdatedAt" timestamp with time zone,
                CONSTRAINT "UX_ea_approval_cycles_ApprovalRequestId_CycleNo" UNIQUE ("ApprovalRequestId", "CycleNo")
            );
            CREATE INDEX IF NOT EXISTS "IX_ea_approval_cycles_ApprovalRequestId" ON public.ea_approval_cycles ("ApprovalRequestId");
            """);

        migrationBuilder.Sql("""
            CREATE SEQUENCE IF NOT EXISTS public.ea_approval_no_seq
                AS bigint
                START WITH 1
                INCREMENT BY 1;

            DO $$
            DECLARE
                next_value bigint;
            BEGIN
                SELECT COALESCE(MAX((substring("ReferenceNo" from '^APR-[0-9]{4}-([0-9]+)$'))::bigint), 0) + 1
                INTO next_value
                FROM public.ea_approval_requests;

                PERFORM setval('public.ea_approval_no_seq', next_value, false);
            END $$;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE IF EXISTS public.ea_approval_cycles;");
        migrationBuilder.Sql("DROP TABLE IF EXISTS public.ea_approval_requests;");
        migrationBuilder.Sql("DROP SEQUENCE IF EXISTS public.ea_approval_no_seq;");
    }
}
