using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace hrms_api.Migrations
{
    /// <inheritdoc />
    public partial class RemoveOnboardingTestModule : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "OnboardingTestResponses");

            migrationBuilder.DropTable(
                name: "OnboardingTestTemplateQuestions");

            migrationBuilder.DropTable(
                name: "OnboardingTestAssignments");

            migrationBuilder.DropTable(
                name: "OnboardingTestBanks");

            migrationBuilder.DropTable(
                name: "OnboardingTestTemplates");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "OnboardingTestBanks" (
                    "QuestionId" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Category" text NOT NULL,
                    "DepartmentId" integer NULL,
                    "DesignationId" integer NULL,
                    "QuestionText" text NOT NULL,
                    "QuestionType" text NOT NULL,
                    "Options" text NULL,
                    "CorrectAnswer" text NULL,
                    "Marks" numeric(8,2) NOT NULL,
                    "DifficultyLevel" text NOT NULL,
                    "IsMandatory" boolean NOT NULL,
                    "IsActive" boolean NOT NULL DEFAULT TRUE,
                    "CreatedBy" text NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    CONSTRAINT "PK_OnboardingTestBanks" PRIMARY KEY ("QuestionId")
                );

                CREATE TABLE IF NOT EXISTS "OnboardingTestTemplates" (
                    "TemplateId" integer GENERATED BY DEFAULT AS IDENTITY,
                    "TemplateName" text NOT NULL,
                    "DepartmentId" integer NULL,
                    "DesignationId" integer NULL,
                    "PassingPercentage" numeric(5,2) NOT NULL,
                    "TotalQuestions" integer NOT NULL,
                    "DurationMinutes" integer NOT NULL,
                    "IsActive" boolean NOT NULL DEFAULT TRUE,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    CONSTRAINT "PK_OnboardingTestTemplates" PRIMARY KEY ("TemplateId")
                );

                CREATE TABLE IF NOT EXISTS "OnboardingTestAssignments" (
                    "AssignmentId" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CandidateId" integer NOT NULL,
                    "OnboardingId" integer NULL,
                    "TemplateId" integer NOT NULL,
                    "AssignedDate" timestamp with time zone NOT NULL,
                    "DueDate" timestamp with time zone NULL,
                    "StartedAt" timestamp with time zone NULL,
                    "SubmittedAt" timestamp with time zone NULL,
                    "TotalMarks" numeric(8,2) NOT NULL,
                    "ObtainedMarks" numeric(8,2) NOT NULL,
                    "Percentage" numeric(5,2) NOT NULL,
                    "ResultStatus" text NOT NULL,
                    "AttemptNo" integer NOT NULL,
                    "AssignedBy" text NULL,
                    "ReviewedBy" text NULL,
                    "ReviewedAt" timestamp with time zone NULL,
                    "ReviewRemarks" text NULL,
                    "Status" text NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    "UpdatedAt" timestamp with time zone NULL,
                    CONSTRAINT "PK_OnboardingTestAssignments" PRIMARY KEY ("AssignmentId"),
                    CONSTRAINT "FK_OnboardingTestAssignments_Candidates_CandidateId" FOREIGN KEY ("CandidateId") REFERENCES "Candidates" ("CandidateId") ON DELETE RESTRICT,
                    CONSTRAINT "FK_OnboardingTestAssignments_OnboardingTestTemplates_TemplateId" FOREIGN KEY ("TemplateId") REFERENCES "OnboardingTestTemplates" ("TemplateId") ON DELETE RESTRICT
                );

                CREATE TABLE IF NOT EXISTS "OnboardingTestTemplateQuestions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "TemplateId" integer NOT NULL,
                    "QuestionId" integer NOT NULL,
                    "Marks" numeric(8,2) NOT NULL,
                    "SortOrder" integer NOT NULL,
                    CONSTRAINT "PK_OnboardingTestTemplateQuestions" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_OnboardingTestTemplateQuestions_OnboardingTestBanks_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "OnboardingTestBanks" ("QuestionId") ON DELETE RESTRICT,
                    CONSTRAINT "FK_OnboardingTestTemplateQuestions_OnboardingTestTemplates_TemplateId" FOREIGN KEY ("TemplateId") REFERENCES "OnboardingTestTemplates" ("TemplateId") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "OnboardingTestResponses" (
                    "ResponseId" integer GENERATED BY DEFAULT AS IDENTITY,
                    "AssignmentId" integer NOT NULL,
                    "QuestionId" integer NOT NULL,
                    "CandidateAnswer" text NULL,
                    "IsCorrect" boolean NULL,
                    "Score" numeric(8,2) NOT NULL,
                    "EvaluatedBy" text NULL,
                    "EvaluatedAt" timestamp with time zone NULL,
                    "EvaluatorRemarks" text NULL,
                    CONSTRAINT "PK_OnboardingTestResponses" PRIMARY KEY ("ResponseId"),
                    CONSTRAINT "FK_OnboardingTestResponses_OnboardingTestAssignments_AssignmentId" FOREIGN KEY ("AssignmentId") REFERENCES "OnboardingTestAssignments" ("AssignmentId") ON DELETE CASCADE,
                    CONSTRAINT "FK_OnboardingTestResponses_OnboardingTestBanks_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "OnboardingTestBanks" ("QuestionId") ON DELETE RESTRICT
                );
                """);
        }
    }
}
