START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727073550_AddScihAnalysis') THEN
    CREATE TABLE "SCIH_Analysis" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RequestId" bigint NOT NULL,
        "AnalysisJson" jsonb NOT NULL DEFAULT '{}',
        "GeneratedByModel" varchar(100),
        "CreatedBy" bigint NOT NULL,
        "CreatedDate" timestamp NOT NULL,
        "ModifiedBy" bigint,
        "ModifiedDate" timestamp,
        CONSTRAINT "PK_SCIH_Analysis" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SCIH_Analysis_SCIH_Request_RequestId" FOREIGN KEY ("RequestId") REFERENCES "SCIH_Request" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727073550_AddScihAnalysis') THEN
    CREATE UNIQUE INDEX "IX_SCIH_Analysis_RequestId" ON "SCIH_Analysis" ("RequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727073550_AddScihAnalysis') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260727073550_AddScihAnalysis', '8.0.10');
    END IF;
END $EF$;
COMMIT;

