CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727061914_InitialCreate') THEN
    CREATE SEQUENCE scih_request_no_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727061914_InitialCreate') THEN
    CREATE TABLE "SCIH_Request" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RequestNo" varchar(30) NOT NULL,
        "Title" varchar(300) NOT NULL,
        "DepartmentId" varchar(300) NOT NULL,
        "RaisedBy" varchar(300) NOT NULL,
        "RaisedAt" timestamp NOT NULL,
        "Status" varchar(30) NOT NULL,
        "CurrentStage" integer NOT NULL,
        "Priority" varchar(20) NOT NULL,
        "OverallProgress" numeric(5,2) NOT NULL,
        "ExpectedBenefit" text NOT NULL,
        "ParentRequestId" bigint,
        "PainPointsJson" jsonb NOT NULL DEFAULT '[]',
        "AttachmentsJson" jsonb NOT NULL DEFAULT '[]',
        "MetaJson" jsonb NOT NULL DEFAULT '{}',
        "IsDeleted" boolean NOT NULL,
        "CreatedBy" bigint NOT NULL,
        "CreatedDate" timestamp NOT NULL,
        "ModifiedBy" bigint,
        "ModifiedDate" timestamp,
        CONSTRAINT "PK_SCIH_Request" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727061914_InitialCreate') THEN
    CREATE TABLE "SCIH_RequestHistory" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RequestId" bigint NOT NULL,
        "Stage" integer NOT NULL,
        "StageName" varchar(100) NOT NULL,
        "Action" varchar(100) NOT NULL,
        "Description" text,
        "PreviousValue" jsonb,
        "NewValue" jsonb,
        "Remarks" text,
        "ActionBy" bigint NOT NULL,
        "ActionDate" timestamp NOT NULL,
        "IPAddress" varchar(100),
        "DeviceInfo" text,
        CONSTRAINT "PK_SCIH_RequestHistory" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SCIH_RequestHistory_SCIH_Request_RequestId" FOREIGN KEY ("RequestId") REFERENCES "SCIH_Request" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727061914_InitialCreate') THEN
    CREATE INDEX "IX_SCIH_Request_DepartmentId" ON "SCIH_Request" ("DepartmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727061914_InitialCreate') THEN
    CREATE INDEX "IX_SCIH_Request_ParentRequestId" ON "SCIH_Request" ("ParentRequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727061914_InitialCreate') THEN
    CREATE INDEX "IX_SCIH_Request_Priority" ON "SCIH_Request" ("Priority");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727061914_InitialCreate') THEN
    CREATE INDEX "IX_SCIH_Request_RaisedAt" ON "SCIH_Request" ("RaisedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727061914_InitialCreate') THEN
    CREATE INDEX "IX_SCIH_Request_RaisedBy" ON "SCIH_Request" ("RaisedBy");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727061914_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_SCIH_Request_RequestNo" ON "SCIH_Request" ("RequestNo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727061914_InitialCreate') THEN
    CREATE INDEX "IX_SCIH_Request_Status" ON "SCIH_Request" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727061914_InitialCreate') THEN
    CREATE INDEX "IX_SCIH_RequestHistory_ActionDate" ON "SCIH_RequestHistory" ("ActionDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727061914_InitialCreate') THEN
    CREATE INDEX "IX_SCIH_RequestHistory_RequestId" ON "SCIH_RequestHistory" ("RequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260727061914_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260727061914_InitialCreate', '8.0.10');
    END IF;
END $EF$;
COMMIT;

