using System.Text;
using System.Text.RegularExpressions;

namespace hrms_api.Services;

public class AiScreeningPromptBuilder : IAiScreeningPromptBuilder
{
    private const int MaxJDLength = 4000;
    private const int MaxResumeLength = 8000;
    private const int MaxPromptLength = 15000;

    public string BuildPrompt(string jdText, string resumeText) =>
        BuildPromptText(jdText, resumeText);

    public AiScreeningPromptBuildResult BuildCompressedPrompt(string jdText, string resumeText)
    {
        var compressedJd = ScreeningTextCompressor.CompressJobDescription(jdText, MaxJDLength);
        var compressedResume = ScreeningTextCompressor.CompressResume(resumeText, MaxResumeLength);
        var prompt = BuildPromptText(compressedJd, compressedResume);

        if (prompt.Length > MaxPromptLength)
        {
            var overBy = prompt.Length - MaxPromptLength;
            var resumeBudget = Math.Max(5000, compressedResume.Length - overBy - 1000);
            compressedResume = ScreeningTextCompressor.CompressResume(resumeText, resumeBudget);
            prompt = BuildPromptText(compressedJd, compressedResume);
        }

        if (prompt.Length > MaxPromptLength)
        {
            var overBy = prompt.Length - MaxPromptLength;
            var jdBudget = Math.Max(2500, compressedJd.Length - overBy - 1000);
            compressedJd = ScreeningTextCompressor.CompressJobDescription(jdText, jdBudget);
            prompt = BuildPromptText(compressedJd, compressedResume);
        }

        return new AiScreeningPromptBuildResult(prompt, compressedJd, compressedResume);
    }

    private static string BuildPromptText(string jdText, string resumeText) => $$"""
        You are a 25-year experienced senior HR recruiter and enterprise talent acquisition expert.
        Evaluate this candidate against the job description like a world-class hiring system.
        Do not do simple keyword matching.
        Judge whether the candidate can actually succeed in this role.

        JOB DESCRIPTION:
        {{jdText}}

        CANDIDATE RESUME:
        {{resumeText}}

        Scoring model:
        Role Fit: 25
        Skill Fit: 20
        Experience Relevance: 15
        Achievement Impact: 15
        Career Stability: 10
        Education & Certifications: 5
        Industry Alignment: 5
        Growth Potential: 5
        Red Flag Deduction: up to -20

        Rules:
        - Be strict but fair.
        - Mandatory JD requirements matter most.
        - Do not reward keyword stuffing.
        - Give marks only when resume shows evidence.
        - If something is not clearly proven, do not assume it.
        - Score must be between 0 and 100.
        - confidenceScore must be between 0 and 100.
        - If evidence is weak, confidence should be low.
        - If resume or JD is unclear, decision should be Pending Review.
        - Score >= 70 means Shortlist.
        - Score < 70 means Reject.
        - Return only valid JSON.
        - No markdown.
        - No explanation outside JSON.

        Return this exact JSON structure and nothing else:
        {
          "overallScore": 0,
          "recommendation": "Strong Hire | Highly Recommended | Recommended | Consider | Weak Match | Reject",
          "decision": "Shortlist | Reject | Pending Review",
          "confidenceScore": 0,
          "riskLevel": "Low | Medium | High",
          "scoreBreakdown": {
            "roleFit": 0,
            "skillFit": 0,
            "experienceRelevance": 0,
            "achievementImpact": 0,
            "careerStability": 0,
            "educationCertification": 0,
            "industryAlignment": 0,
            "growthPotential": 0,
            "redFlagDeduction": 0
          },
          "matchedSkills": [],
          "missingSkills": [],
          "strengths": [],
          "concerns": [],
          "redFlags": [],
          "interviewFocusAreas": [],
          "shortSummary": ""
        }
        """;

    private static class ScreeningTextCompressor
    {
        private static readonly Regex SpaceRegex = new(@"\s+", RegexOptions.Compiled);
        private static readonly Regex BulletRegex = new(@"^[\s\-\*\u2022\u25cf\u25cb\u25aa\d\.\)\(]+", RegexOptions.Compiled);
        private static readonly Regex PageNumberRegex = new(@"^(page\s*)?\d+\s*(of\s*\d+)?$", RegexOptions.IgnoreCase | RegexOptions.Compiled);
        private static readonly Regex ContactRegex = new(@"(\+?\d[\d\s\-()]{7,}|[\w\.\-]+@[\w\.\-]+\.\w+|https?://\S+|www\.\S+|linkedin\.com/\S+)", RegexOptions.IgnoreCase | RegexOptions.Compiled);
        private static readonly Regex FooterRegex = new(@"^(confidential|private and confidential|resume|curriculum vitae|cv|job description|jd|generated by|downloaded from)\b", RegexOptions.IgnoreCase | RegexOptions.Compiled);
        private static readonly Regex AddressRegex = new(@"\b(address|permanent address|current address|residential address)\b", RegexOptions.IgnoreCase | RegexOptions.Compiled);

        private static readonly SectionSpec[] JdSections =
        [
            new("Mandatory Skills", 1, ["mandatory skills", "must have skills", "required skills", "skills required", "key skills", "technical skills"]),
            new("Must-Have Criteria", 1, ["must-have", "must have", "minimum criteria", "eligibility", "mandatory requirements", "required qualifications"]),
            new("Required Experience", 2, ["required experience", "experience required", "experience", "years of experience"]),
            new("Responsibilities", 3, ["responsibilities", "roles and responsibilities", "duties", "what you will do", "job responsibilities"]),
            new("Preferred Skills", 4, ["preferred skills", "good to have", "nice to have", "preferred qualifications", "plus"]),
            new("Education Requirements", 6, ["education", "qualification", "qualifications", "degree", "academic"]),
            new("Job Title", 8, ["job title", "designation", "position", "role"]),
            new("Department", 8, ["department", "function", "team"]),
            new("Industry/Domain", 8, ["industry", "domain", "business domain", "sector"]),
            new("Location", 8, ["location", "work location", "job location", "city"])
        ];

        private static readonly SectionSpec[] ResumeSections =
        [
            new("Skills", 1, ["skills", "technical skills", "core skills", "key skills", "competencies", "expertise"]),
            new("Total Experience", 2, ["total experience", "professional experience", "experience summary", "years of experience"]),
            new("Work Experience", 2, ["work experience", "professional experience", "employment history", "career history", "experience"]),
            new("Current and Previous Job Titles", 2, ["current role", "current position", "designation", "job title", "roles"]),
            new("Projects", 4, ["projects", "key projects", "project experience", "major projects"]),
            new("Achievements", 5, ["achievements", "awards", "accomplishments", "recognition", "highlights"]),
            new("Education", 6, ["education", "academic", "academics", "qualification", "qualifications"]),
            new("Certifications", 7, ["certifications", "certificates", "certification", "licenses"]),
            new("Candidate Summary", 8, ["summary", "profile", "objective", "professional summary", "career summary"]),
            new("Technologies/Tools", 8, ["technologies", "tools", "platforms", "software", "tech stack"])
        ];

        private static readonly string[] ResumeExcludedHeadings =
        [
            "address", "personal details", "personal information", "references", "reference",
            "declaration", "hobbies", "interests", "contact", "contact information"
        ];

        public static string CompressJobDescription(string text, int maxLength) =>
            Compress(text, JdSections, [], maxLength);

        public static string CompressResume(string text, int maxLength) =>
            Compress(text, ResumeSections, ResumeExcludedHeadings, maxLength);

        private static string Compress(string text, SectionSpec[] specs, string[] excludedHeadings, int maxLength)
        {
            var lines = CleanLines(text, removeContactLines: excludedHeadings.Length > 0);
            var extracted = ExtractSections(lines, specs, excludedHeadings);
            AddKeywordFallbacks(lines, specs, extracted, excludedHeadings);

            var ordered = extracted.Values
                .Where(s => s.Lines.Count > 0)
                .OrderBy(s => s.Spec.Priority)
                .ThenBy(s => Array.IndexOf(specs, s.Spec))
                .ToList();

            if (ordered.Count == 0)
                return BudgetLines(lines, maxLength);

            return BuildBudgetedSections(ordered, maxLength);
        }

        private static List<string> CleanLines(string text, bool removeContactLines)
        {
            var result = new List<string>();
            var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            foreach (var rawLine in (text ?? string.Empty).Replace("\r", "\n").Split('\n'))
            {
                var line = NormalizeLine(rawLine);
                if (line.Length < 2 || PageNumberRegex.IsMatch(line) || FooterRegex.IsMatch(line))
                    continue;

                if (removeContactLines && (ContactRegex.IsMatch(line) || AddressRegex.IsMatch(line)))
                    continue;

                var signature = NormalizeSignature(line);
                if (signature.Length < 2 || !seen.Add(signature))
                    continue;

                result.Add(line);
            }

            return result;
        }

        private static Dictionary<string, ExtractedSection> ExtractSections(
            List<string> lines,
            SectionSpec[] specs,
            string[] excludedHeadings)
        {
            var sections = specs.ToDictionary(s => s.Title, s => new ExtractedSection(s), StringComparer.OrdinalIgnoreCase);
            SectionSpec? current = null;
            var skipCurrent = false;

            foreach (var line in lines)
            {
                var heading = MatchHeading(line, specs, excludedHeadings);
                if (heading.IsExcluded)
                {
                    current = null;
                    skipCurrent = true;
                    continue;
                }

                if (heading.Spec is not null)
                {
                    current = heading.Spec;
                    skipCurrent = false;
                    var inline = GetInlineHeadingContent(line);
                    if (!string.IsNullOrWhiteSpace(inline))
                        sections[current.Title].Add(inline);
                    continue;
                }

                if (!skipCurrent && current is not null)
                    sections[current.Title].Add(line);
            }

            return sections;
        }

        private static void AddKeywordFallbacks(
            List<string> lines,
            SectionSpec[] specs,
            Dictionary<string, ExtractedSection> sections,
            string[] excludedHeadings)
        {
            foreach (var line in lines)
            {
                if (IsExcluded(line, excludedHeadings))
                    continue;

                foreach (var spec in specs.OrderBy(s => s.Priority))
                {
                    if (sections[spec.Title].Lines.Count >= 20)
                        continue;

                    if (spec.HeadingKeywords.Any(k => ContainsKeyword(line, k)))
                    {
                        sections[spec.Title].Add(GetInlineHeadingContent(line) ?? line);
                        break;
                    }
                }
            }
        }

        private static string BuildBudgetedSections(List<ExtractedSection> sections, int maxLength)
        {
            var sb = new StringBuilder();

            foreach (var section in sections)
            {
                var header = section.Spec.Title + ":";
                if (sb.Length + header.Length + 2 > maxLength)
                    break;

                if (sb.Length > 0)
                    sb.AppendLine();

                sb.AppendLine(header);

                foreach (var line in section.Lines)
                {
                    var item = "- " + line;
                    if (sb.Length + item.Length + 1 > maxLength)
                        break;
                    sb.AppendLine(item);
                }
            }

            return sb.ToString().Trim();
        }

        private static string BudgetLines(List<string> lines, int maxLength)
        {
            var sb = new StringBuilder();
            foreach (var line in lines)
            {
                if (sb.Length + line.Length + 3 > maxLength)
                    break;
                sb.Append("- ").AppendLine(line);
            }

            return sb.ToString().Trim();
        }

        private static HeadingMatch MatchHeading(string line, SectionSpec[] specs, string[] excludedHeadings)
        {
            var headingText = ExtractHeadingText(line);
            if (headingText is null)
                return new HeadingMatch(null, false);

            if (IsExcluded(headingText, excludedHeadings))
                return new HeadingMatch(null, true);

            var spec = specs.FirstOrDefault(s => s.HeadingKeywords.Any(k => HeadingEquals(headingText, k)));
            return new HeadingMatch(spec, false);
        }

        private static string? ExtractHeadingText(string line)
        {
            var colonIndex = line.IndexOf(':');
            if (colonIndex >= 0 && colonIndex <= 60)
                return line[..colonIndex].Trim();

            if (line.Length <= 70 && !line.EndsWith('.') && line.Count(char.IsLetter) >= 3)
                return line.Trim();

            return null;
        }

        private static string? GetInlineHeadingContent(string line)
        {
            var colonIndex = line.IndexOf(':');
            if (colonIndex < 0 || colonIndex == line.Length - 1)
                return null;

            return NormalizeLine(line[(colonIndex + 1)..]);
        }

        private static bool IsExcluded(string line, string[] excludedHeadings) =>
            excludedHeadings.Any(h => HeadingEquals(line, h) || ContainsKeyword(line, h));

        private static bool HeadingEquals(string value, string keyword)
        {
            var normalizedValue = NormalizeSignature(value);
            var normalizedKeyword = NormalizeSignature(keyword);
            return normalizedValue == normalizedKeyword || normalizedValue.Contains(normalizedKeyword);
        }

        private static bool ContainsKeyword(string value, string keyword) =>
            NormalizeSignature(value).Contains(NormalizeSignature(keyword));

        private static string NormalizeLine(string value)
        {
            var cleaned = value
                .Replace('\t', ' ')
                .Replace('|', ' ')
                .Replace('\u00a0', ' ');

            cleaned = BulletRegex.Replace(cleaned, "");
            cleaned = SpaceRegex.Replace(cleaned, " ").Trim();
            return cleaned;
        }

        private static string NormalizeSignature(string value)
        {
            var chars = value.ToLowerInvariant()
                .Where(c => char.IsLetterOrDigit(c) || char.IsWhiteSpace(c))
                .ToArray();
            return SpaceRegex.Replace(new string(chars), " ").Trim();
        }

        private sealed record SectionSpec(string Title, int Priority, string[] HeadingKeywords);
        private sealed record HeadingMatch(SectionSpec? Spec, bool IsExcluded);

        private sealed class ExtractedSection
        {
            private readonly HashSet<string> _seen = new(StringComparer.OrdinalIgnoreCase);

            public ExtractedSection(SectionSpec spec)
            {
                Spec = spec;
            }

            public SectionSpec Spec { get; }
            public List<string> Lines { get; } = [];

            public void Add(string line)
            {
                line = NormalizeLine(line);
                if (line.Length < 2)
                    return;

                var signature = NormalizeSignature(line);
                if (_seen.Add(signature))
                    Lines.Add(line);
            }
        }
    }
}
